---
apiVersion: v1
kind: Service
metadata:
  name: urlshortener-query
  labels:
    #
    app.kubernetes.io/name: urlshortener-query
    app.kubernetes.io/instance: urlshortener-query
    app.kubernetes.io/version: "1.0"
spec:
  type: NodePort
  ports:
    - name: rest-service
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: urlshortener-query
    app.kubernetes.io/instance: urlshortener-query
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener-query
  labels:
    #
    app.kubernetes.io/name: urlshortener-query
    app.kubernetes.io/instance: urlshortener-query
    app.kubernetes.io/version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: urlshortener-query
      app.kubernetes.io/instance: urlshortener-query
  template:
    metadata:
      labels:
        app.kubernetes.io/name: urlshortener-query
        app.kubernetes.io/instance: urlshortener-query
        app.kubernetes.io/version: "1.0"
    spec:
      imagePullSecrets:
        - name: artifactory-docker-credentials
      containers:
        - name: urlshortener-query
          image: "registry.hub.docker.com/carvalhorr/urlshortener-query:1.0"
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 8081
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
